### ISSUE TITLE
Issue installing extension

### ISSUE THREAD

**Issue by dylancaponi** [curlconverter/curlconverter-vscode#5]
Thanks for pushing out that feature so fast!

Unfortunately, I can't seem to download the extension now:
```[2022-08-31 13:46:36.229] [renderer1] [error] XHR failed: Download: XHR failed
    at Q.downloadExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169038)
    at async Q.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:168169)
```

**Comment by dylancaponi** [comment]
Restarting vscode a few times fixed this.
